// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdysmbluidbrmsthxhyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeXNtYmx1aWRicm1zdGh4aHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDExNDAsImV4cCI6MjA2MTYxNzE0MH0.Ujus27I93gzfxcZSQGbiUUyQ5KpDSCzrDBbCdi5P7YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);